version: "3.3"
services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: flask-examples:latest
        working_dir: /opt/examples/
        command: bash run.sh
        ports:
            - 5000:5000
        volumes:
            - ./examples/:/opt/examples/
        environment:
            FLASK_APP: poema.py
        stdin_open: true
        tty: true
        expose:
            - 5000
